### PR TITLE
Implement pipelined begin for executable query

### PR DESCRIPTION
**Pull request by thelonelyvulpes**
Optimizes running executable queries by removing a server round trip.

### CODE REVIEW

**Review by AndyHeap-NeoTech — COMMENTED** [review]
Looks good, pretty straightforward. Again we find ourselves passing parameters down the stack. Was going to question the switch to using Session instead of AsyncSession, then realised it is just a wrapper method for Session.

**Comment by thelonelyvulpes** [comment]
Awaiting: https://github.com/neo4j-drivers/testkit/pull/588

**Comment by thelonelyvulpes** [comment]
> Looks good, pretty straightforward. Again we find ourselves passing parameters down the stack. Was going to question the switch to using Session instead of AsyncSession, then realised it is just a wrapper method for Session.

I have moved the parameter into an object, going forward we can push values on to that instead of adding a parameter to several methods. There's still a couple more bolt protocol methods that could do with a parameter object treatment but I think tackling them one by one keeps the size of changes down.

**Review by AndyHeap-NeoTech — APPROVED** [review]
LGTM

**Pull request merged**
