### PR TITLE
Add example for multiple async transactions

### PR DESCRIPTION
**Pull request by bigmontz**

### CODE REVIEW

**Comment by AndyHeap-NeoTech** [comment]
Is there a reason this is on the 4.2 branch? I thought it would be the 4.3 one.

**Comment by bigmontz** [comment]
> Is there a reason this is on the 4.2 branch? I thought it would be the 4.3 one.

When we started to work on this change, the docs 4.3 branch didn't exist. So we made the change in 4.2 and we will port the 4.3

**Comment by AndyHeap-NeoTech** [comment]
[Review and get working PRs for code examples from Antonio and Greg](https://trello.com/c/XR51RERr/74-review-and-get-working-prs-for-code-examples-from-antonio-and-greg)

**Review by AndyHeap-NeoTech — COMMENTED** [review]
All looks good and merged.

**Pull request merged**
